### ISSUE TITLE
Passar a estrutura do mallinfo e a função para o arquivo do memalloc

### ISSUE THREAD

**Issue by Sergiorezende22** [Softawii/memalloc#11]
Preciso pensar em uma arquitetura melhor para organizar o mallinfo

**Comment by yaansz** [comment]
oq vc acha que precisa mudar?

**Comment by yaansz** [comment]
Pode usar um nested namespace, n sei o quao correto isso é but

```
namespace A::B::C {
}

```
https://www.geeksforgeeks.org/g-fact-62/
